bases:
  - ../default

patchesStrategicMerge:
  - manager_deployment_patch.yaml
  - |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: overwhelm-system
      $patch: delete

patchesJson6902:
  - target: # We use Json6902 patches for inline replacement patches  which are not possible with Strategic Merge patches
      group: apps
      version: v1
      kind: Deployment
      name: overwhelm-controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value: <GOTEMPLATE> toYaml .Values.deployment.resources  | indent 10 </GOTEMPLATE>
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: applications.core.expediagroup.com
    path: application_crd_older_version_patch.yaml

