bases:
  - ../default

patchesStrategicMerge:
  - manager_deployment_patch.yaml
  - |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: overwhelm-system
      $patch: delete

patchesJson6902: # We use Json6902 patches for inline replacement patches which are not possible with Strategic Merge patches
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: overwhelm-controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value: <GOTEMPLATE> toYaml .Values.deployment.resources  | indent 10 </GOTEMPLATE>
