apiVersion: apps/v1
kind: Deployment
metadata:
  name: overwhelm-controller-manager
  namespace: overwhelm-system
spec:
  replicas: "{{ .Values.deployment.replicas }}"
  template:
    metadata:
      $patch: replace
      annotations: "{{ toYaml .Values.deployment.annotations  | indent 8 }}"
      labels: "{{ toYaml .Values.deployment.labels  | indent 8 }}"
    spec:
      containers:
      - name: manager
        image: "{{ .Values.deployment.image.manager.repository }}:{{ .Values.deployment.image.manager.tag }}"
      - name: kube-rbac-proxy
        image: "{{ .Values.deployment.image.kubeRbacProxy.repository }}:{{ .Values.deployment.image.kubeRbacProxy.tag }}"