# Use <GOTEMPLATE></GOTEMPLATE> tags for Go template delimiters to be inserted by the script/helm-charts/update.go script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overwhelm-controller-manager
  namespace: overwhelm-system
spec:
  replicas: <GOTEMPLATE> .Values.deployment.replicas </GOTEMPLATE>
  template:
    metadata:
      $patch: replace
      annotations: <GOTEMPLATE> toYaml .Values.deployment.annotations  | indent 8 </GOTEMPLATE>
      labels: <GOTEMPLATE> toYaml .Values.deployment.labels  | indent 8 </GOTEMPLATE>
    spec:
      containers:
      - name: manager
        image: <GOTEMPLATE> .Values.deployment.image.manager.repository </GOTEMPLATE>:<GOTEMPLATE> .Values.deployment.image.manager.tag </GOTEMPLATE>
      - name: kube-rbac-proxy
        image: <GOTEMPLATE> .Values.deployment.image.kubeRbacProxy.repository </GOTEMPLATE>:<GOTEMPLATE> .Values.deployment.image.kubeRbacProxy.tag </GOTEMPLATE>