apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: overwhelm-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: overwhelm-manager-role
subjects:
- kind: ServiceAccount
  name: overwhelm-controller-manager
  namespace: overwhelm-system
