apiVersion: v1
data:
  cluster: some-cluster
  region: us-west-2
  account: "1234"
  segment: some-segment
kind: ConfigMap
metadata:
  name: cluster-properties
  namespace: kube-public
  labels:
    "k8s.overwhelm.com/render-values-source": "cluster"
