# This is a sample of the Application Resource that, when deployed in a cluster, triggers the
# overwhelm operator to perform its reconciliation logic
apiVersion: core.expediagroup.com/v1alpha1
kind: Application
metadata:
  name: application-sample
  namespace: app-namespace
spec:
  spec:
    interval: 10m
    chart:
      spec:
        chart: some-chart-name
        version: '0.0.1'
        sourceRef:
          name: public-helm-virtual
          kind: HelmRepository
  data:
    values.yaml: |-
      deployment : hello-world
      account : {{ .cluster.account }}
      region : {{ .cluster.region }}
      environment : {{ .egdata.environment }}




